server:
  port: 8080
  mode: "debug"

database:
  type: "sqlite"
  sqlite:
    path: "./scifind.db"

nats:
  url: "nats://localhost:4222"
  cluster_id: "scifind-cluster"
  client_id: "scifind-backend"
  max_reconnects: 10
  reconnect_wait: "2s"
  timeout: "5s"
  
  # Embedded NATS server configuration
  embedded:
    enabled: true  # Enable embedded NATS server for single executable deployment
    host: "0.0.0.0"
    port: 4222
    log_level: "INFO"
    log_file: ""
    
    # Clustering configuration (for future multi-instance deployment)
    cluster:
      name: "scifind-cluster"
      host: "0.0.0.0"
      port: 6222
      routes: []
    
    # Gateway configuration (for super cluster support)
    gateway:
      name: "scifind-gateway"
      host: "0.0.0.0"
      port: 7222
    
    # HTTP monitoring interface
    monitor:
      host: "0.0.0.0"
      port: 8222
    
    # Accounts configuration
    accounts:
      system_account: "$SYS"
    
    # Resource limits
    limits:
      max_connections: 10000
      max_payload: "1MB"
      max_pending: "64MB"
  
  # TLS configuration (optional, for production mTLS)
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""
    verify_and_map: false
    insecure_skip_verify: false
    
    # mTLS client authentication
    client_auth:
      enabled: false
      cert_file: ""
      key_file: ""
  
  # JetStream persistent messaging configuration
  jetstream:
    enabled: true
    domain: ""
    store_dir: "./jetstream"
    max_memory: "1GB"
    max_storage: "10GB"
    sync_interval: "2m"
  
  # Key-Value store for caching
  kv_store:
    enabled: true
    bucket: "scifind-cache"
    ttl: "1h"
  
  # Object store for large data
  object_store:
    enabled: true
    bucket: "scifind-objects"

# Add your API keys for enhanced functionality
providers:
  arxiv:
    enabled: true
    base_url: "http://export.arxiv.org/api/query"
    rate_limit: "3s"  # ArXiv requires 3 second delay between requests
    timeout: "30s"
  semantic_scholar:
    enabled: true
  exa:
    enabled: false
  tavily:
    enabled: false