# ============================================================================
# SciFIND Backend Configuration
# Production-ready configuration based on Phase 3 specifications
# Environment variables override these settings with SCIFIND_ prefix
# ============================================================================

# Server Configuration
server:
  port: 8080
  host: "0.0.0.0"
  mode: "release"  # debug, release, test
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  max_header_bytes: 1048576  # 1MB
  enable_gzip: true
  enable_cors: true
  enable_metrics: true

# Database Configuration
database:
  type: "postgres"  # postgres, sqlite
  postgresql:
    dsn: "postgres://scifind:scifind@localhost:5432/scifind?sslmode=disable"
    max_connections: 25
    max_idle: 10
    max_lifetime: "1h"
    max_idle_time: "30m"
    auto_migrate: true
  sqlite:
    path: "./scifind.db"
    auto_migrate: true

# NATS Configuration
nats:
  url: "nats://localhost:4222"
  cluster_id: "scifind-cluster"
  client_id: "scifind-backend"
  max_reconnects: 10
  reconnect_wait: "2s"
  timeout: "5s"
  ping_interval: 30  # seconds
  max_pings_out: 2
  
  # TLS Configuration (optional)
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""
  
  # JetStream Configuration
  jetstream:
    enabled: true
    domain: ""
    max_memory: "1GB"
    max_storage: "10GB"
  
  # Key-Value Store Configuration
  kv_store:
    enabled: true
    bucket: "scifind-cache"
    ttl: "1h"
  
  # Object Store Configuration
  object_store:
    enabled: true
    bucket: "scifind-objects"

# External Provider Configuration
providers:
  arxiv:
    enabled: true
    base_url: "http://export.arxiv.org/api/query"
    rate_limit: "3s"  # ArXiv requires 3 second delay between requests
    timeout: "30s"
  
  semantic_scholar:
    enabled: true
    api_key: ""  # Set via SCIFIND_PROVIDERS_SEMANTIC_SCHOLAR_API_KEY
    base_url: "https://api.semanticscholar.org/graph/v1"
    timeout: "15s"
  
  exa:
    enabled: false  # Requires API key
    api_key: ""  # Set via SCIFIND_PROVIDERS_EXA_API_KEY
    base_url: "https://api.exa.ai"
    timeout: "15s"
  
  tavily:
    enabled: false  # Requires API key
    api_key: ""  # Set via SCIFIND_PROVIDERS_TAVILY_API_KEY
    base_url: "https://api.tavily.com"
    timeout: "15s"

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  add_source: false
  output: "stdout"  # stdout, stderr, file
  file_path: ""  # Required when output is 'file'

# Security Configuration
security:
  api_keys: []  # API keys for authentication (if needed)
  
  # Rate Limiting
  rate_limit:
    enabled: true
    requests: 100  # Requests per window
    window: "1m"   # Time window
    burst_size: 10 # Burst allowance
  
  # CORS Configuration
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: "12h"

# Circuit Breaker Configuration
circuit:
  enabled: true
  failure_threshold: 5    # Failures before opening circuit
  success_threshold: 3    # Successes required to close circuit
  timeout: "60s"          # How long circuit stays open
  max_requests: 10        # Max requests in half-open state
  sliding_window: "60s"   # Time window for failure counting
  min_request_count: 10   # Minimum requests before circuit can open

# Retry Configuration
retry:
  enabled: true
  max_attempts: 3
  initial_delay: "1s"
  max_delay: "30s"
  backoff_factor: 2.0
  jitter: true

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_path: "/health"
  metrics_path: "/metrics"
