// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"log/slog"
	"scifind-backend/internal/api"
	"scifind-backend/internal/api/handlers"
	"scifind-backend/internal/config"
	"scifind-backend/internal/messaging"
	"scifind-backend/internal/messaging/embedded"
	"scifind-backend/internal/repository"
	"scifind-backend/internal/services"
)

// Injectors from wire.go:

// InitializeApplication creates a fully configured application using Wire
func InitializeApplication(ctx context.Context) (*Application, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	database, err := ProvideDatabase(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	manager, err := ProvideEmbeddedManager(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	client := ProvideMessagingFromEmbedded(manager)
	container := ProvideRepositories(database, logger)
	servicesContainer := ProvideServices(container, client, logger)
	handlersContainer := ProvideHandlers(servicesContainer, logger)
	searchService := ProvideConcreteSearchService(container, client, logger)
	paperService := ProvideConcretePaperService(container, client, logger)
	authorService := ProvideConcreteAuthorService(container, client, logger)
	healthHandler := ProvideConcreteHealthHandler(servicesContainer, logger)
	engine := ProvideRouter(searchService, paperService, authorService, healthHandler, logger)
	application := NewApplication(configConfig, database, client, manager, servicesContainer, handlersContainer, engine, logger)
	return application, func() {
	}, nil
}

// wire.go:

// Application represents the complete application with all dependencies
type Application struct {
	Config          *config.Config
	Database        *repository.Database
	Messaging       *messaging.Client
	EmbeddedManager *embedded.Manager
	Services        *services.Container
	Handlers        *handlers.Container
	Router          *gin.Engine
	Logger          *slog.Logger
}

// NewApplication creates the main application instance
func NewApplication(
	cfg *config.Config,
	db *repository.Database, messaging2 *messaging.Client,
	embeddedManager *embedded.Manager, services2 *services.Container, handlers2 *handlers.Container,
	router *gin.Engine,
	logger *slog.Logger,
) *Application {
	return &Application{
		Config:          cfg,
		Database:        db,
		Messaging:       messaging2,
		EmbeddedManager: embeddedManager,
		Services:        services2,
		Handlers:        handlers2,
		Router:          router,
		Logger:          logger,
	}
}

// Provider sets for Wire dependency injection
var ConfigProviderSet = wire.NewSet(config.LoadConfig, ProvideLogger)

var DatabaseProviderSet = wire.NewSet(
	ProvideDatabase,
	ProvideRepositories,
)

var MessagingProviderSet = wire.NewSet(
	ProvideEmbeddedManager,
	ProvideMessagingFromEmbedded,
)

var ServicesProviderSet = wire.NewSet(
	ProvideServices,
)

var HandlersProviderSet = wire.NewSet(
	ProvideHandlers,
)

var APIProviderSet = wire.NewSet(
	ProvideConcreteSearchService,
	ProvideConcretePaperService,
	ProvideConcreteAuthorService,
	ProvideConcreteHealthHandler,
	ProvideRouter,
)

// ApplicationProviderSet combines all provider sets
var ApplicationProviderSet = wire.NewSet(
	ConfigProviderSet,
	DatabaseProviderSet,
	MessagingProviderSet,
	ServicesProviderSet,
	HandlersProviderSet,
	APIProviderSet,
	NewApplication,
)

// ProvideLogger creates a structured logger instance
func ProvideLogger(cfg *config.Config) (*slog.Logger, error) {
	logger, err := config.NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	return logger, nil
}

// ProvideDatabase creates a database instance
func ProvideDatabase(cfg *config.Config, logger *slog.Logger) (*repository.Database, error) {
	return repository.NewDatabase(cfg, logger)
}

// ProvideRepositories creates repository instances
func ProvideRepositories(db *repository.Database, logger *slog.Logger) *repository.Container {
	return repository.NewContainer(db.DB, logger)
}

// ProvideEmbeddedManager creates an embedded NATS manager
func ProvideEmbeddedManager(cfg *config.Config, logger *slog.Logger) (*embedded.Manager, error) {
	return embedded.NewManager(&cfg.NATS, logger)
}

// ProvideMessagingFromEmbedded provides messaging client from embedded manager
func ProvideMessagingFromEmbedded(embeddedManager *embedded.Manager) *messaging.Client {
	return embeddedManager.GetClient()
}

// ProvideServices creates service instances
func ProvideServices(repos *repository.Container, messaging2 *messaging.Client, logger *slog.Logger) *services.Container {
	return services.NewContainer(repos, messaging2, logger)
}

// ProvideHandlers creates HTTP handler instances
func ProvideHandlers(services2 *services.Container, logger *slog.Logger) *handlers.Container {
	return handlers.NewContainer(services2, logger)
}

// ProvideConcreteSearchService creates a concrete search service
func ProvideConcreteSearchService(repos *repository.Container, messaging2 *messaging.Client, logger *slog.Logger) *services.SearchService {
	return services.NewSearchService(repos.Search, repos.Paper, messaging2, logger).(*services.SearchService)
}

// ProvideConcretePaperService creates a concrete paper service
func ProvideConcretePaperService(repos *repository.Container, messaging2 *messaging.Client, logger *slog.Logger) *services.PaperService {
	return services.NewPaperService(repos.Paper, messaging2, logger).(*services.PaperService)
}

// ProvideConcreteAuthorService creates a concrete author service
func ProvideConcreteAuthorService(repos *repository.Container, messaging2 *messaging.Client, logger *slog.Logger) *services.AuthorService {
	return services.NewAuthorService(repos.Author, repos.Paper, messaging2, logger).(*services.AuthorService)
}

// ProvideConcreteHealthHandler creates a concrete health handler
func ProvideConcreteHealthHandler(services2 *services.Container, logger *slog.Logger) *handlers.HealthHandler {
	return handlers.NewHealthHandler(services2.Health, logger)
}

// ProvideRouter creates the HTTP router
func ProvideRouter(
	searchService *services.SearchService,
	paperService *services.PaperService,
	authorService *services.AuthorService,
	healthHandler *handlers.HealthHandler,
	logger *slog.Logger,
) *gin.Engine {
	return api.NewRouter(
		searchService,
		paperService,
		authorService,
		healthHandler,
		logger,
	)
}
