// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://scifind.ai/terms",
        "contact": {
            "name": "SciFIND Support",
            "url": "https://scifind.ai/support",
            "email": "support@scifind.ai"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns comprehensive health status for all system components",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Full health check",
                "responses": {
                    "200": {
                        "description": "Health status\\",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Returns a simple liveness probe to verify the service is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Liveness status\\",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Returns readiness status including dependencies health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "Health status\\",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Health status\\",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns a simple liveness probe to verify the service is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Liveness status\\",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/authors": {
            "get": {
                "description": "Get a paginated list of authors with optional search",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authors"
                ],
                "summary": "List authors",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of results to return (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search query for author names",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of authors with pagination info",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/authors/{id}": {
            "get": {
                "description": "Retrieve a specific author by their ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authors"
                ],
                "summary": "Get an author by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Author ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Author details",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/authors/{id}/papers": {
            "get": {
                "description": "Get a paginated list of papers by a specific author",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authors"
                ],
                "summary": "Get papers by an author",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Author ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Author papers with pagination info",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/papers": {
            "get": {
                "description": "Get a paginated list of papers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "papers"
                ],
                "summary": "List papers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of results to return (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of papers with pagination info",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new paper (currently not implemented)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "papers"
                ],
                "summary": "Create a new paper",
                "parameters": [
                    {
                        "description": "Paper data",
                        "name": "paper",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created paper",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/papers/{id}": {
            "get": {
                "description": "Retrieve a specific paper by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "papers"
                ],
                "summary": "Get a paper by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Paper ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paper details",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing paper (currently not implemented)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "papers"
                ],
                "summary": "Update a paper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Paper ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated paper data",
                        "name": "paper",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated paper",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a paper (currently not implemented)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "papers"
                ],
                "summary": "Delete a paper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Paper ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/search": {
            "get": {
                "description": "Search for academic papers across multiple providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search for academic papers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of providers (arxiv,semantic_scholar,exa,tavily)",
                        "name": "providers",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date filter (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Author filter",
                        "name": "author",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Journal filter",
                        "name": "journal",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category filter",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scifind-backend_internal_services.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/search/papers/{provider}/{id}": {
            "get": {
                "description": "Retrieve a specific paper by provider name and paper ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Get a specific paper",
                "parameters": [
                    {
                        "enum": [
                            "arxiv",
                            "semantic_scholar",
                            "exa",
                            "tavily"
                        ],
                        "type": "string",
                        "description": "Provider name",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Paper ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scifind-backend_internal_services.PaperResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/search/providers": {
            "get": {
                "description": "Get information about available search providers and their status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Get available search providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scifind-backend_internal_services.ProviderStatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/search/providers/metrics": {
            "get": {
                "description": "Get performance metrics for search providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Get search provider metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Specific provider name",
                        "name": "provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scifind-backend_internal_services.ProviderMetricsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/search/providers/{provider}/configure": {
            "put": {
                "description": "Update the configuration of a specific search provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Configure a search provider",
                "parameters": [
                    {
                        "enum": [
                            "arxiv",
                            "semantic_scholar",
                            "exa",
                            "tavily"
                        ],
                        "type": "string",
                        "description": "Provider name",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Provider configuration",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scifind-backend_internal_providers.ProviderConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scifind-backend_internal_services.ProviderConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_api_handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_models.Author": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "affiliation": {
                    "type": "string",
                    "maxLength": 500
                },
                "citation_count": {
                    "type": "integer",
                    "minimum": 0
                },
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "h_index": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "orcid": {
                    "type": "string"
                },
                "paper_count": {
                    "description": "Metrics",
                    "type": "integer",
                    "minimum": 0
                },
                "papers": {
                    "description": "Relationships",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_models.Paper"
                    }
                },
                "research_areas": {
                    "description": "Research profile",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "website": {
                    "type": "string",
                    "maxLength": 2048
                }
            }
        },
        "scifind-backend_internal_models.Category": {
            "type": "object",
            "required": [
                "id",
                "name",
                "source",
                "source_code"
            ],
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_models.Category"
                    }
                },
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "level": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "paper_count": {
                    "description": "Usage statistics",
                    "type": "integer",
                    "minimum": 0
                },
                "papers": {
                    "description": "Relationships",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_models.Paper"
                    }
                },
                "parent": {
                    "description": "Hierarchy relationships",
                    "allOf": [
                        {
                            "$ref": "#/definitions/scifind-backend_internal_models.Category"
                        }
                    ]
                },
                "parent_id": {
                    "type": "string"
                },
                "source": {
                    "description": "Classification metadata",
                    "type": "string",
                    "enum": [
                        "arxiv",
                        "acm",
                        "ieee",
                        "manual"
                    ]
                },
                "source_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_models.Paper": {
            "type": "object",
            "required": [
                "authors",
                "id",
                "language",
                "source_id",
                "source_provider",
                "title"
            ],
            "properties": {
                "abstract": {
                    "type": "string",
                    "maxLength": 10000
                },
                "arxiv_id": {
                    "type": "string"
                },
                "authors": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_models.Author"
                    }
                },
                "categories": {
                    "description": "Classification and metrics",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_models.Category"
                    }
                },
                "citation_count": {
                    "description": "Citation metrics",
                    "type": "integer",
                    "minimum": 0
                },
                "citations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "doi": {
                    "type": "string"
                },
                "extracted_data": {
                    "type": "string"
                },
                "full_text": {
                    "description": "Content analysis",
                    "type": "string"
                },
                "id": {
                    "description": "Primary identifiers",
                    "type": "string"
                },
                "issue": {
                    "type": "string",
                    "maxLength": 50
                },
                "journal": {
                    "description": "Publication details",
                    "type": "string",
                    "maxLength": 500
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "string"
                },
                "pages": {
                    "type": "string",
                    "maxLength": 100
                },
                "pdf_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "processing_state": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "processing",
                        "completed",
                        "failed"
                    ]
                },
                "published_at": {
                    "type": "string"
                },
                "quality_score": {
                    "description": "Quality and processing",
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0
                },
                "references": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "source_id": {
                    "type": "string"
                },
                "source_provider": {
                    "description": "Source tracking",
                    "type": "string",
                    "enum": [
                        "arxiv",
                        "semantic_scholar",
                        "exa",
                        "tavily",
                        "manual"
                    ]
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "description": "Core metadata",
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "description": "URLs and access",
                    "type": "string",
                    "maxLength": 2048
                },
                "volume": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "scifind-backend_internal_providers.CacheConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "key_prefix": {
                    "type": "string"
                },
                "max_size": {
                    "type": "integer"
                },
                "ttl": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "scifind-backend_internal_providers.CircuitBreakerConfig": {
            "type": "object",
            "properties": {
                "failure_threshold": {
                    "type": "integer"
                },
                "interval": {
                    "$ref": "#/definitions/time.Duration"
                },
                "max_requests": {
                    "type": "integer"
                },
                "success_threshold": {
                    "type": "integer"
                },
                "timeout": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "scifind-backend_internal_providers.ProviderConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "api_secret": {
                    "type": "string"
                },
                "base_url": {
                    "description": "API configuration",
                    "type": "string"
                },
                "cache": {
                    "description": "Caching",
                    "allOf": [
                        {
                            "$ref": "#/definitions/scifind-backend_internal_providers.CacheConfig"
                        }
                    ]
                },
                "circuit_breaker": {
                    "description": "Circuit breaker",
                    "allOf": [
                        {
                            "$ref": "#/definitions/scifind-backend_internal_providers.CircuitBreakerConfig"
                        }
                    ]
                },
                "custom": {
                    "description": "Custom settings",
                    "type": "object",
                    "additionalProperties": true
                },
                "enabled": {
                    "type": "boolean"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "max_retries": {
                    "type": "integer"
                },
                "name": {
                    "description": "Basic config",
                    "type": "string"
                },
                "rate_limit": {
                    "description": "Rate limiting",
                    "allOf": [
                        {
                            "$ref": "#/definitions/scifind-backend_internal_providers.RateLimitConfig"
                        }
                    ]
                },
                "retry_delay": {
                    "$ref": "#/definitions/time.Duration"
                },
                "timeout": {
                    "description": "Timeouts",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                }
            }
        },
        "scifind-backend_internal_providers.ProviderError": {
            "type": "object",
            "properties": {
                "error": {},
                "provider": {
                    "type": "string"
                },
                "retryable": {
                    "type": "boolean"
                },
                "type": {
                    "description": "timeout, rate_limit, network, parse, etc.",
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_providers.ProviderMetrics": {
            "type": "object",
            "properties": {
                "avg_response_time": {
                    "description": "Performance metrics",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                },
                "avg_results_per_query": {
                    "type": "number"
                },
                "cached_requests": {
                    "type": "integer"
                },
                "circuit_close_count": {
                    "type": "integer"
                },
                "circuit_open_count": {
                    "description": "Circuit breaker",
                    "type": "integer"
                },
                "failed_requests": {
                    "type": "integer"
                },
                "max_response_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "min_response_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "network_errors": {
                    "type": "integer"
                },
                "p95_response_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "parse_errors": {
                    "type": "integer"
                },
                "rate_limit_errors": {
                    "type": "integer"
                },
                "rate_limit_hits": {
                    "description": "Rate limiting",
                    "type": "integer"
                },
                "rate_limit_resets": {
                    "type": "integer"
                },
                "successful_requests": {
                    "type": "integer"
                },
                "timeout_errors": {
                    "description": "Error statistics",
                    "type": "integer"
                },
                "total_requests": {
                    "description": "Request statistics",
                    "type": "integer"
                },
                "total_results": {
                    "description": "Result statistics",
                    "type": "integer"
                },
                "window_end": {
                    "type": "string"
                },
                "window_start": {
                    "description": "Time window",
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_providers.ProviderStatus": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "Versioning",
                    "type": "string"
                },
                "avg_response_time": {
                    "description": "Performance",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                },
                "circuit_state": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "healthy": {
                    "type": "boolean"
                },
                "last_check": {
                    "type": "string"
                },
                "last_error": {},
                "last_updated": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rate_limited": {
                    "description": "Rate limiting",
                    "type": "boolean"
                },
                "reset_time": {
                    "type": "string"
                },
                "success_rate": {
                    "type": "number"
                }
            }
        },
        "scifind-backend_internal_providers.RateLimitConfig": {
            "type": "object",
            "properties": {
                "backoff_duration": {
                    "$ref": "#/definitions/time.Duration"
                },
                "burst_size": {
                    "type": "integer"
                },
                "requests_per_hour": {
                    "type": "integer"
                },
                "requests_per_minute": {
                    "type": "integer"
                },
                "requests_per_second": {
                    "type": "integer"
                }
            }
        },
        "scifind-backend_internal_services.PaperResponse": {
            "type": "object",
            "properties": {
                "paper": {
                    "$ref": "#/definitions/scifind-backend_internal_models.Paper"
                },
                "source": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_services.ProviderConfigResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "provider_name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/scifind-backend_internal_providers.ProviderStatus"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_services.ProviderMetricsResponse": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "providers": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/scifind-backend_internal_providers.ProviderMetrics"
                    }
                },
                "start_time": {
                    "type": "string"
                },
                "time_range": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_services.ProviderStatusResponse": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/scifind-backend_internal_providers.ProviderStatus"
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "scifind-backend_internal_services.SearchResponse": {
            "type": "object",
            "properties": {
                "aggregation_strategy": {
                    "type": "string"
                },
                "cache_hits": {
                    "type": "integer"
                },
                "duration": {
                    "$ref": "#/definitions/time.Duration"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_providers.ProviderError"
                    }
                },
                "papers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scifind-backend_internal_models.Paper"
                    }
                },
                "partial_failure": {
                    "type": "boolean"
                },
                "providers_failed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "providers_used": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "query": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "result_count": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key for authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "SciFIND Backend API",
	Description:      "This is the main API server for SciFIND, a scientific literature discovery platform. It provides endpoints for searching academic papers across multiple providers, managing papers and authors, and retrieving scientific literature metadata.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
